apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: lbcf-validate
webhooks:
  - name: driver.lbcf.tkestack.io
    rules:
      - apiGroups:
          - "lbcf.tkestack.io"
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - loadbalancerdrivers
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMyakNDQWNJQ0NRQ0J3Z2Z3d3ZBK3hEQU5CZ2txaGtpRzl3MEJBUXNGQURBdU1Rc3dDUVlEVlFRR0V3SkQKVGpFUU1BNEdBMVVFQ2d3SFZHVnVZMlZ1ZERFTk1Bc0dBMVVFQXd3RVRFSkRSakFnRncweU1ERXlNekF3TkRJMQpNVEJhR0E4eU1USXdNVEl3TmpBME1qVXhNRm93TGpFTE1Ba0dBMVVFQmhNQ1EwNHhFREFPQmdOVkJBb01CMVJsCmJtTmxiblF4RFRBTEJnTlZCQU1NQkV4Q1EwWXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUsKQW9JQkFRRFhtNzVvVnVaWkh5eC9mMzNtamIwalZ3WkdISnArRGtmN3pySmFDcGRPSFZCbDh1WnlvS2Rmc3A0VQpHNnlXdFIvdmJ6d216TjJFd0JVcTFxRHdUaFVxWTVQU05JUTZlK0cwOThyOWhGOWlvZEswQ1NITDFBbFJsWmZCCk1oMTk4MXhpUDBKcnF1MkczNUZrbVZ1VERkUktXRGs4K1JmSDNZY01lSzNaSlBoVVJKR3pjUlByL0s2a01KUlAKZXpIRUxqR3FmbXBMcEo4YzQ5MkxZNXJtN2FhbGZWMmk2NUpFci9LNHdjMSs2elpBcjdMM21zM21vNHVkOE9adQo5Wi82cTNicVFVWjdtemZRNkhJMU5aNWlINi9oSGNaNHBRTXE0TWpZOGpaNUZyakpFRzF2aUF1RmRPZnp3RmNpCmVvUmdaOHo5NjdQQWhlZTMwVkFmRERQOVlVTXJBZ01CQUFFd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFCdloKQUNaejhEYk9uOGEralZlcUtlb1VEZVB4bzdqZm53bXZQTDVjS3B3QzF1UzZFZ1pOeFNHVkJLWUVTMk4wdFpwdwpvU2tjSEFpZ3Mxb3doeTdvL1pYZlh6RXhRdHJBL1JZQVBOZjYxNncwUjBiRFV4U2lUZTJPQm45RGs2aWlYdGFDCnNXZVdHSnRldEw0T0pLU2UrZkUwcVFIcE5NSWtPYkwyeDdtNGxTRk54UUFDd09yVmlvdEUxenlWY1hsZkpEUHYKczA0SEV6NldQY2laUHZEY1kvQ0VKbC8zMEUwMFZKVDg4WDNuZUE2a0NVTG9NVzcyMW9xc0pRSUxjOGVCbkFwRAo3VDJ0UnVEMnhqRzd3SE9GMzRQaUx5VUZNVFNxZm9neXN5ZVFtRzRJb1Q1T3FwUnRFYUd3b2J1dTgrVDd1bnVkCkFtZDRiWElUL3ZhbVBsdEo2dWM9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: lbcf-controller
        namespace: kube-system
        path: "/validate-load-balancer-driver"
    failurePolicy: Fail
  - name: lb.lbcf.tkestack.io
    rules:
      - apiGroups:
          - "lbcf.tkestack.io"
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - loadbalancers
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMyakNDQWNJQ0NRQ0J3Z2Z3d3ZBK3hEQU5CZ2txaGtpRzl3MEJBUXNGQURBdU1Rc3dDUVlEVlFRR0V3SkQKVGpFUU1BNEdBMVVFQ2d3SFZHVnVZMlZ1ZERFTk1Bc0dBMVVFQXd3RVRFSkRSakFnRncweU1ERXlNekF3TkRJMQpNVEJhR0E4eU1USXdNVEl3TmpBME1qVXhNRm93TGpFTE1Ba0dBMVVFQmhNQ1EwNHhFREFPQmdOVkJBb01CMVJsCmJtTmxiblF4RFRBTEJnTlZCQU1NQkV4Q1EwWXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUsKQW9JQkFRRFhtNzVvVnVaWkh5eC9mMzNtamIwalZ3WkdISnArRGtmN3pySmFDcGRPSFZCbDh1WnlvS2Rmc3A0VQpHNnlXdFIvdmJ6d216TjJFd0JVcTFxRHdUaFVxWTVQU05JUTZlK0cwOThyOWhGOWlvZEswQ1NITDFBbFJsWmZCCk1oMTk4MXhpUDBKcnF1MkczNUZrbVZ1VERkUktXRGs4K1JmSDNZY01lSzNaSlBoVVJKR3pjUlByL0s2a01KUlAKZXpIRUxqR3FmbXBMcEo4YzQ5MkxZNXJtN2FhbGZWMmk2NUpFci9LNHdjMSs2elpBcjdMM21zM21vNHVkOE9adQo5Wi82cTNicVFVWjdtemZRNkhJMU5aNWlINi9oSGNaNHBRTXE0TWpZOGpaNUZyakpFRzF2aUF1RmRPZnp3RmNpCmVvUmdaOHo5NjdQQWhlZTMwVkFmRERQOVlVTXJBZ01CQUFFd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFCdloKQUNaejhEYk9uOGEralZlcUtlb1VEZVB4bzdqZm53bXZQTDVjS3B3QzF1UzZFZ1pOeFNHVkJLWUVTMk4wdFpwdwpvU2tjSEFpZ3Mxb3doeTdvL1pYZlh6RXhRdHJBL1JZQVBOZjYxNncwUjBiRFV4U2lUZTJPQm45RGs2aWlYdGFDCnNXZVdHSnRldEw0T0pLU2UrZkUwcVFIcE5NSWtPYkwyeDdtNGxTRk54UUFDd09yVmlvdEUxenlWY1hsZkpEUHYKczA0SEV6NldQY2laUHZEY1kvQ0VKbC8zMEUwMFZKVDg4WDNuZUE2a0NVTG9NVzcyMW9xc0pRSUxjOGVCbkFwRAo3VDJ0UnVEMnhqRzd3SE9GMzRQaUx5VUZNVFNxZm9neXN5ZVFtRzRJb1Q1T3FwUnRFYUd3b2J1dTgrVDd1bnVkCkFtZDRiWElUL3ZhbVBsdEo2dWM9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: lbcf-controller
        namespace: kube-system
        path: "/validate-load-balancer"
    failurePolicy: Fail
  - name: backendgroup.lbcf.tkestack.io
    rules:
      - apiGroups:
          - "lbcf.tkestack.io"
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - backendgroups
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMyakNDQWNJQ0NRQ0J3Z2Z3d3ZBK3hEQU5CZ2txaGtpRzl3MEJBUXNGQURBdU1Rc3dDUVlEVlFRR0V3SkQKVGpFUU1BNEdBMVVFQ2d3SFZHVnVZMlZ1ZERFTk1Bc0dBMVVFQXd3RVRFSkRSakFnRncweU1ERXlNekF3TkRJMQpNVEJhR0E4eU1USXdNVEl3TmpBME1qVXhNRm93TGpFTE1Ba0dBMVVFQmhNQ1EwNHhFREFPQmdOVkJBb01CMVJsCmJtTmxiblF4RFRBTEJnTlZCQU1NQkV4Q1EwWXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUsKQW9JQkFRRFhtNzVvVnVaWkh5eC9mMzNtamIwalZ3WkdISnArRGtmN3pySmFDcGRPSFZCbDh1WnlvS2Rmc3A0VQpHNnlXdFIvdmJ6d216TjJFd0JVcTFxRHdUaFVxWTVQU05JUTZlK0cwOThyOWhGOWlvZEswQ1NITDFBbFJsWmZCCk1oMTk4MXhpUDBKcnF1MkczNUZrbVZ1VERkUktXRGs4K1JmSDNZY01lSzNaSlBoVVJKR3pjUlByL0s2a01KUlAKZXpIRUxqR3FmbXBMcEo4YzQ5MkxZNXJtN2FhbGZWMmk2NUpFci9LNHdjMSs2elpBcjdMM21zM21vNHVkOE9adQo5Wi82cTNicVFVWjdtemZRNkhJMU5aNWlINi9oSGNaNHBRTXE0TWpZOGpaNUZyakpFRzF2aUF1RmRPZnp3RmNpCmVvUmdaOHo5NjdQQWhlZTMwVkFmRERQOVlVTXJBZ01CQUFFd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFCdloKQUNaejhEYk9uOGEralZlcUtlb1VEZVB4bzdqZm53bXZQTDVjS3B3QzF1UzZFZ1pOeFNHVkJLWUVTMk4wdFpwdwpvU2tjSEFpZ3Mxb3doeTdvL1pYZlh6RXhRdHJBL1JZQVBOZjYxNncwUjBiRFV4U2lUZTJPQm45RGs2aWlYdGFDCnNXZVdHSnRldEw0T0pLU2UrZkUwcVFIcE5NSWtPYkwyeDdtNGxTRk54UUFDd09yVmlvdEUxenlWY1hsZkpEUHYKczA0SEV6NldQY2laUHZEY1kvQ0VKbC8zMEUwMFZKVDg4WDNuZUE2a0NVTG9NVzcyMW9xc0pRSUxjOGVCbkFwRAo3VDJ0UnVEMnhqRzd3SE9GMzRQaUx5VUZNVFNxZm9neXN5ZVFtRzRJb1Q1T3FwUnRFYUd3b2J1dTgrVDd1bnVkCkFtZDRiWElUL3ZhbVBsdEo2dWM9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: lbcf-controller
        namespace: kube-system
        path: "/validate-backend-group"
    failurePolicy: Fail
  - name: bind.lbcf.tkestack.io
    rules:
      - apiGroups:
          - "lbcf.tkestack.io"
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - binds
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMyakNDQWNJQ0NRQ0J3Z2Z3d3ZBK3hEQU5CZ2txaGtpRzl3MEJBUXNGQURBdU1Rc3dDUVlEVlFRR0V3SkQKVGpFUU1BNEdBMVVFQ2d3SFZHVnVZMlZ1ZERFTk1Bc0dBMVVFQXd3RVRFSkRSakFnRncweU1ERXlNekF3TkRJMQpNVEJhR0E4eU1USXdNVEl3TmpBME1qVXhNRm93TGpFTE1Ba0dBMVVFQmhNQ1EwNHhFREFPQmdOVkJBb01CMVJsCmJtTmxiblF4RFRBTEJnTlZCQU1NQkV4Q1EwWXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUsKQW9JQkFRRFhtNzVvVnVaWkh5eC9mMzNtamIwalZ3WkdISnArRGtmN3pySmFDcGRPSFZCbDh1WnlvS2Rmc3A0VQpHNnlXdFIvdmJ6d216TjJFd0JVcTFxRHdUaFVxWTVQU05JUTZlK0cwOThyOWhGOWlvZEswQ1NITDFBbFJsWmZCCk1oMTk4MXhpUDBKcnF1MkczNUZrbVZ1VERkUktXRGs4K1JmSDNZY01lSzNaSlBoVVJKR3pjUlByL0s2a01KUlAKZXpIRUxqR3FmbXBMcEo4YzQ5MkxZNXJtN2FhbGZWMmk2NUpFci9LNHdjMSs2elpBcjdMM21zM21vNHVkOE9adQo5Wi82cTNicVFVWjdtemZRNkhJMU5aNWlINi9oSGNaNHBRTXE0TWpZOGpaNUZyakpFRzF2aUF1RmRPZnp3RmNpCmVvUmdaOHo5NjdQQWhlZTMwVkFmRERQOVlVTXJBZ01CQUFFd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFCdloKQUNaejhEYk9uOGEralZlcUtlb1VEZVB4bzdqZm53bXZQTDVjS3B3QzF1UzZFZ1pOeFNHVkJLWUVTMk4wdFpwdwpvU2tjSEFpZ3Mxb3doeTdvL1pYZlh6RXhRdHJBL1JZQVBOZjYxNncwUjBiRFV4U2lUZTJPQm45RGs2aWlYdGFDCnNXZVdHSnRldEw0T0pLU2UrZkUwcVFIcE5NSWtPYkwyeDdtNGxTRk54UUFDd09yVmlvdEUxenlWY1hsZkpEUHYKczA0SEV6NldQY2laUHZEY1kvQ0VKbC8zMEUwMFZKVDg4WDNuZUE2a0NVTG9NVzcyMW9xc0pRSUxjOGVCbkFwRAo3VDJ0UnVEMnhqRzd3SE9GMzRQaUx5VUZNVFNxZm9neXN5ZVFtRzRJb1Q1T3FwUnRFYUd3b2J1dTgrVDd1bnVkCkFtZDRiWElUL3ZhbVBsdEo2dWM9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: lbcf-controller
        namespace: kube-system
        path: "/validate-bind"
    failurePolicy: Fail
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: lbcf-mutate
webhooks:
  - name: driver.lbcf.tkestack.io
    rules:
      - apiGroups:
          - "lbcf.tkestack.io"
        apiVersions:
          - v1beta1
        operations:
          - CREATE
        resources:
          - loadbalancerdrivers
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMyakNDQWNJQ0NRQ0J3Z2Z3d3ZBK3hEQU5CZ2txaGtpRzl3MEJBUXNGQURBdU1Rc3dDUVlEVlFRR0V3SkQKVGpFUU1BNEdBMVVFQ2d3SFZHVnVZMlZ1ZERFTk1Bc0dBMVVFQXd3RVRFSkRSakFnRncweU1ERXlNekF3TkRJMQpNVEJhR0E4eU1USXdNVEl3TmpBME1qVXhNRm93TGpFTE1Ba0dBMVVFQmhNQ1EwNHhFREFPQmdOVkJBb01CMVJsCmJtTmxiblF4RFRBTEJnTlZCQU1NQkV4Q1EwWXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUsKQW9JQkFRRFhtNzVvVnVaWkh5eC9mMzNtamIwalZ3WkdISnArRGtmN3pySmFDcGRPSFZCbDh1WnlvS2Rmc3A0VQpHNnlXdFIvdmJ6d216TjJFd0JVcTFxRHdUaFVxWTVQU05JUTZlK0cwOThyOWhGOWlvZEswQ1NITDFBbFJsWmZCCk1oMTk4MXhpUDBKcnF1MkczNUZrbVZ1VERkUktXRGs4K1JmSDNZY01lSzNaSlBoVVJKR3pjUlByL0s2a01KUlAKZXpIRUxqR3FmbXBMcEo4YzQ5MkxZNXJtN2FhbGZWMmk2NUpFci9LNHdjMSs2elpBcjdMM21zM21vNHVkOE9adQo5Wi82cTNicVFVWjdtemZRNkhJMU5aNWlINi9oSGNaNHBRTXE0TWpZOGpaNUZyakpFRzF2aUF1RmRPZnp3RmNpCmVvUmdaOHo5NjdQQWhlZTMwVkFmRERQOVlVTXJBZ01CQUFFd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFCdloKQUNaejhEYk9uOGEralZlcUtlb1VEZVB4bzdqZm53bXZQTDVjS3B3QzF1UzZFZ1pOeFNHVkJLWUVTMk4wdFpwdwpvU2tjSEFpZ3Mxb3doeTdvL1pYZlh6RXhRdHJBL1JZQVBOZjYxNncwUjBiRFV4U2lUZTJPQm45RGs2aWlYdGFDCnNXZVdHSnRldEw0T0pLU2UrZkUwcVFIcE5NSWtPYkwyeDdtNGxTRk54UUFDd09yVmlvdEUxenlWY1hsZkpEUHYKczA0SEV6NldQY2laUHZEY1kvQ0VKbC8zMEUwMFZKVDg4WDNuZUE2a0NVTG9NVzcyMW9xc0pRSUxjOGVCbkFwRAo3VDJ0UnVEMnhqRzd3SE9GMzRQaUx5VUZNVFNxZm9neXN5ZVFtRzRJb1Q1T3FwUnRFYUd3b2J1dTgrVDd1bnVkCkFtZDRiWElUL3ZhbVBsdEo2dWM9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: lbcf-controller
        namespace: kube-system
        path: "/mutate-load-balancer-driver"
    failurePolicy: Fail
  - name: lb.lbcf.tkestack.io
    rules:
      - apiGroups:
          - "lbcf.tkestack.io"
        apiVersions:
          - v1beta1
        operations:
          - CREATE
        resources:
          - loadbalancers
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMyakNDQWNJQ0NRQ0J3Z2Z3d3ZBK3hEQU5CZ2txaGtpRzl3MEJBUXNGQURBdU1Rc3dDUVlEVlFRR0V3SkQKVGpFUU1BNEdBMVVFQ2d3SFZHVnVZMlZ1ZERFTk1Bc0dBMVVFQXd3RVRFSkRSakFnRncweU1ERXlNekF3TkRJMQpNVEJhR0E4eU1USXdNVEl3TmpBME1qVXhNRm93TGpFTE1Ba0dBMVVFQmhNQ1EwNHhFREFPQmdOVkJBb01CMVJsCmJtTmxiblF4RFRBTEJnTlZCQU1NQkV4Q1EwWXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUsKQW9JQkFRRFhtNzVvVnVaWkh5eC9mMzNtamIwalZ3WkdISnArRGtmN3pySmFDcGRPSFZCbDh1WnlvS2Rmc3A0VQpHNnlXdFIvdmJ6d216TjJFd0JVcTFxRHdUaFVxWTVQU05JUTZlK0cwOThyOWhGOWlvZEswQ1NITDFBbFJsWmZCCk1oMTk4MXhpUDBKcnF1MkczNUZrbVZ1VERkUktXRGs4K1JmSDNZY01lSzNaSlBoVVJKR3pjUlByL0s2a01KUlAKZXpIRUxqR3FmbXBMcEo4YzQ5MkxZNXJtN2FhbGZWMmk2NUpFci9LNHdjMSs2elpBcjdMM21zM21vNHVkOE9adQo5Wi82cTNicVFVWjdtemZRNkhJMU5aNWlINi9oSGNaNHBRTXE0TWpZOGpaNUZyakpFRzF2aUF1RmRPZnp3RmNpCmVvUmdaOHo5NjdQQWhlZTMwVkFmRERQOVlVTXJBZ01CQUFFd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFCdloKQUNaejhEYk9uOGEralZlcUtlb1VEZVB4bzdqZm53bXZQTDVjS3B3QzF1UzZFZ1pOeFNHVkJLWUVTMk4wdFpwdwpvU2tjSEFpZ3Mxb3doeTdvL1pYZlh6RXhRdHJBL1JZQVBOZjYxNncwUjBiRFV4U2lUZTJPQm45RGs2aWlYdGFDCnNXZVdHSnRldEw0T0pLU2UrZkUwcVFIcE5NSWtPYkwyeDdtNGxTRk54UUFDd09yVmlvdEUxenlWY1hsZkpEUHYKczA0SEV6NldQY2laUHZEY1kvQ0VKbC8zMEUwMFZKVDg4WDNuZUE2a0NVTG9NVzcyMW9xc0pRSUxjOGVCbkFwRAo3VDJ0UnVEMnhqRzd3SE9GMzRQaUx5VUZNVFNxZm9neXN5ZVFtRzRJb1Q1T3FwUnRFYUd3b2J1dTgrVDd1bnVkCkFtZDRiWElUL3ZhbVBsdEo2dWM9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: lbcf-controller
        namespace: kube-system
        path: "/mutate-load-balancer"
    failurePolicy: Fail
  - name: backendgroup.lbcf.tkestack.io
    rules:
      - apiGroups:
          - "lbcf.tkestack.io"
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - backendgroups
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMyakNDQWNJQ0NRQ0J3Z2Z3d3ZBK3hEQU5CZ2txaGtpRzl3MEJBUXNGQURBdU1Rc3dDUVlEVlFRR0V3SkQKVGpFUU1BNEdBMVVFQ2d3SFZHVnVZMlZ1ZERFTk1Bc0dBMVVFQXd3RVRFSkRSakFnRncweU1ERXlNekF3TkRJMQpNVEJhR0E4eU1USXdNVEl3TmpBME1qVXhNRm93TGpFTE1Ba0dBMVVFQmhNQ1EwNHhFREFPQmdOVkJBb01CMVJsCmJtTmxiblF4RFRBTEJnTlZCQU1NQkV4Q1EwWXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUsKQW9JQkFRRFhtNzVvVnVaWkh5eC9mMzNtamIwalZ3WkdISnArRGtmN3pySmFDcGRPSFZCbDh1WnlvS2Rmc3A0VQpHNnlXdFIvdmJ6d216TjJFd0JVcTFxRHdUaFVxWTVQU05JUTZlK0cwOThyOWhGOWlvZEswQ1NITDFBbFJsWmZCCk1oMTk4MXhpUDBKcnF1MkczNUZrbVZ1VERkUktXRGs4K1JmSDNZY01lSzNaSlBoVVJKR3pjUlByL0s2a01KUlAKZXpIRUxqR3FmbXBMcEo4YzQ5MkxZNXJtN2FhbGZWMmk2NUpFci9LNHdjMSs2elpBcjdMM21zM21vNHVkOE9adQo5Wi82cTNicVFVWjdtemZRNkhJMU5aNWlINi9oSGNaNHBRTXE0TWpZOGpaNUZyakpFRzF2aUF1RmRPZnp3RmNpCmVvUmdaOHo5NjdQQWhlZTMwVkFmRERQOVlVTXJBZ01CQUFFd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFCdloKQUNaejhEYk9uOGEralZlcUtlb1VEZVB4bzdqZm53bXZQTDVjS3B3QzF1UzZFZ1pOeFNHVkJLWUVTMk4wdFpwdwpvU2tjSEFpZ3Mxb3doeTdvL1pYZlh6RXhRdHJBL1JZQVBOZjYxNncwUjBiRFV4U2lUZTJPQm45RGs2aWlYdGFDCnNXZVdHSnRldEw0T0pLU2UrZkUwcVFIcE5NSWtPYkwyeDdtNGxTRk54UUFDd09yVmlvdEUxenlWY1hsZkpEUHYKczA0SEV6NldQY2laUHZEY1kvQ0VKbC8zMEUwMFZKVDg4WDNuZUE2a0NVTG9NVzcyMW9xc0pRSUxjOGVCbkFwRAo3VDJ0UnVEMnhqRzd3SE9GMzRQaUx5VUZNVFNxZm9neXN5ZVFtRzRJb1Q1T3FwUnRFYUd3b2J1dTgrVDd1bnVkCkFtZDRiWElUL3ZhbVBsdEo2dWM9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: lbcf-controller
        namespace: kube-system
        path: "/mutate-backend-broup"
    failurePolicy: Fail
  - name: bind.lbcf.tkestack.io
    rules:
      - apiGroups:
          - "lbcf.tkestack.io"
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - binds
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMyakNDQWNJQ0NRQ0J3Z2Z3d3ZBK3hEQU5CZ2txaGtpRzl3MEJBUXNGQURBdU1Rc3dDUVlEVlFRR0V3SkQKVGpFUU1BNEdBMVVFQ2d3SFZHVnVZMlZ1ZERFTk1Bc0dBMVVFQXd3RVRFSkRSakFnRncweU1ERXlNekF3TkRJMQpNVEJhR0E4eU1USXdNVEl3TmpBME1qVXhNRm93TGpFTE1Ba0dBMVVFQmhNQ1EwNHhFREFPQmdOVkJBb01CMVJsCmJtTmxiblF4RFRBTEJnTlZCQU1NQkV4Q1EwWXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUsKQW9JQkFRRFhtNzVvVnVaWkh5eC9mMzNtamIwalZ3WkdISnArRGtmN3pySmFDcGRPSFZCbDh1WnlvS2Rmc3A0VQpHNnlXdFIvdmJ6d216TjJFd0JVcTFxRHdUaFVxWTVQU05JUTZlK0cwOThyOWhGOWlvZEswQ1NITDFBbFJsWmZCCk1oMTk4MXhpUDBKcnF1MkczNUZrbVZ1VERkUktXRGs4K1JmSDNZY01lSzNaSlBoVVJKR3pjUlByL0s2a01KUlAKZXpIRUxqR3FmbXBMcEo4YzQ5MkxZNXJtN2FhbGZWMmk2NUpFci9LNHdjMSs2elpBcjdMM21zM21vNHVkOE9adQo5Wi82cTNicVFVWjdtemZRNkhJMU5aNWlINi9oSGNaNHBRTXE0TWpZOGpaNUZyakpFRzF2aUF1RmRPZnp3RmNpCmVvUmdaOHo5NjdQQWhlZTMwVkFmRERQOVlVTXJBZ01CQUFFd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFCdloKQUNaejhEYk9uOGEralZlcUtlb1VEZVB4bzdqZm53bXZQTDVjS3B3QzF1UzZFZ1pOeFNHVkJLWUVTMk4wdFpwdwpvU2tjSEFpZ3Mxb3doeTdvL1pYZlh6RXhRdHJBL1JZQVBOZjYxNncwUjBiRFV4U2lUZTJPQm45RGs2aWlYdGFDCnNXZVdHSnRldEw0T0pLU2UrZkUwcVFIcE5NSWtPYkwyeDdtNGxTRk54UUFDd09yVmlvdEUxenlWY1hsZkpEUHYKczA0SEV6NldQY2laUHZEY1kvQ0VKbC8zMEUwMFZKVDg4WDNuZUE2a0NVTG9NVzcyMW9xc0pRSUxjOGVCbkFwRAo3VDJ0UnVEMnhqRzd3SE9GMzRQaUx5VUZNVFNxZm9neXN5ZVFtRzRJb1Q1T3FwUnRFYUd3b2J1dTgrVDd1bnVkCkFtZDRiWElUL3ZhbVBsdEo2dWM9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: lbcf-controller
        namespace: kube-system
        path: "/mutate-bind"
    failurePolicy: Fail
