/*
 * Tencent is pleased to support the open source community by making TKEStack
 * available.
 *
 * Copyright (C) 2012-2020 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use
 * this file except in compliance with the License. You may obtain a copy of the
 * License at
 *
 * https://opensource.org/licenses/Apache-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OF ANY KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1beta1 "tkestack.io/lb-controlling-framework/pkg/apis/lbcf.tkestack.io/v1beta1"
	scheme "tkestack.io/lb-controlling-framework/pkg/client-go/clientset/versioned/scheme"
)

// BackendGroupsGetter has a method to return a BackendGroupInterface.
// A group's client should implement this interface.
type BackendGroupsGetter interface {
	BackendGroups(namespace string) BackendGroupInterface
}

// BackendGroupInterface has methods to work with BackendGroup resources.
type BackendGroupInterface interface {
	Create(ctx context.Context, backendGroup *v1beta1.BackendGroup, opts v1.CreateOptions) (*v1beta1.BackendGroup, error)
	Update(ctx context.Context, backendGroup *v1beta1.BackendGroup, opts v1.UpdateOptions) (*v1beta1.BackendGroup, error)
	UpdateStatus(ctx context.Context, backendGroup *v1beta1.BackendGroup, opts v1.UpdateOptions) (*v1beta1.BackendGroup, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.BackendGroup, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.BackendGroupList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.BackendGroup, err error)
	BackendGroupExpansion
}

// backendGroups implements BackendGroupInterface
type backendGroups struct {
	client rest.Interface
	ns     string
}

// newBackendGroups returns a BackendGroups
func newBackendGroups(c *LbcfV1beta1Client, namespace string) *backendGroups {
	return &backendGroups{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the backendGroup, and returns the corresponding backendGroup object, and an error if there is any.
func (c *backendGroups) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.BackendGroup, err error) {
	result = &v1beta1.BackendGroup{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("backendgroups").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of BackendGroups that match those selectors.
func (c *backendGroups) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.BackendGroupList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.BackendGroupList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("backendgroups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested backendGroups.
func (c *backendGroups) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("backendgroups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a backendGroup and creates it.  Returns the server's representation of the backendGroup, and an error, if there is any.
func (c *backendGroups) Create(ctx context.Context, backendGroup *v1beta1.BackendGroup, opts v1.CreateOptions) (result *v1beta1.BackendGroup, err error) {
	result = &v1beta1.BackendGroup{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("backendgroups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(backendGroup).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a backendGroup and updates it. Returns the server's representation of the backendGroup, and an error, if there is any.
func (c *backendGroups) Update(ctx context.Context, backendGroup *v1beta1.BackendGroup, opts v1.UpdateOptions) (result *v1beta1.BackendGroup, err error) {
	result = &v1beta1.BackendGroup{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("backendgroups").
		Name(backendGroup.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(backendGroup).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *backendGroups) UpdateStatus(ctx context.Context, backendGroup *v1beta1.BackendGroup, opts v1.UpdateOptions) (result *v1beta1.BackendGroup, err error) {
	result = &v1beta1.BackendGroup{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("backendgroups").
		Name(backendGroup.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(backendGroup).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the backendGroup and deletes it. Returns an error if one occurs.
func (c *backendGroups) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("backendgroups").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *backendGroups) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("backendgroups").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched backendGroup.
func (c *backendGroups) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.BackendGroup, err error) {
	result = &v1beta1.BackendGroup{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("backendgroups").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
