/*
 * Tencent is pleased to support the open source community by making TKEStack
 * available.
 *
 * Copyright (C) 2012-2020 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use
 * this file except in compliance with the License. You may obtain a copy of the
 * License at
 *
 * https://opensource.org/licenses/Apache-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OF ANY KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1 "tkestack.io/lb-controlling-framework/pkg/apis/lbcf.tkestack.io/v1"
	scheme "tkestack.io/lb-controlling-framework/pkg/client-go/clientset/versioned/scheme"
)

// BindsGetter has a method to return a BindInterface.
// A group's client should implement this interface.
type BindsGetter interface {
	Binds(namespace string) BindInterface
}

// BindInterface has methods to work with Bind resources.
type BindInterface interface {
	Create(ctx context.Context, bind *v1.Bind, opts metav1.CreateOptions) (*v1.Bind, error)
	Update(ctx context.Context, bind *v1.Bind, opts metav1.UpdateOptions) (*v1.Bind, error)
	UpdateStatus(ctx context.Context, bind *v1.Bind, opts metav1.UpdateOptions) (*v1.Bind, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.Bind, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.BindList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Bind, err error)
	BindExpansion
}

// binds implements BindInterface
type binds struct {
	client rest.Interface
	ns     string
}

// newBinds returns a Binds
func newBinds(c *LbcfV1Client, namespace string) *binds {
	return &binds{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the bind, and returns the corresponding bind object, and an error if there is any.
func (c *binds) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.Bind, err error) {
	result = &v1.Bind{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("binds").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Binds that match those selectors.
func (c *binds) List(ctx context.Context, opts metav1.ListOptions) (result *v1.BindList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.BindList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("binds").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested binds.
func (c *binds) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("binds").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a bind and creates it.  Returns the server's representation of the bind, and an error, if there is any.
func (c *binds) Create(ctx context.Context, bind *v1.Bind, opts metav1.CreateOptions) (result *v1.Bind, err error) {
	result = &v1.Bind{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("binds").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(bind).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a bind and updates it. Returns the server's representation of the bind, and an error, if there is any.
func (c *binds) Update(ctx context.Context, bind *v1.Bind, opts metav1.UpdateOptions) (result *v1.Bind, err error) {
	result = &v1.Bind{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("binds").
		Name(bind.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(bind).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *binds) UpdateStatus(ctx context.Context, bind *v1.Bind, opts metav1.UpdateOptions) (result *v1.Bind, err error) {
	result = &v1.Bind{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("binds").
		Name(bind.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(bind).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the bind and deletes it. Returns an error if one occurs.
func (c *binds) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("binds").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *binds) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("binds").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched bind.
func (c *binds) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Bind, err error) {
	result = &v1.Bind{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("binds").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
