/*
 * Tencent is pleased to support the open source community by making TKEStack
 * available.
 *
 * Copyright (C) 2012-2020 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use
 * this file except in compliance with the License. You may obtain a copy of the
 * License at
 *
 * https://opensource.org/licenses/Apache-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OF ANY KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1beta1 "tkestack.io/lb-controlling-framework/pkg/apis/lbcf.tkestack.io/v1beta1"
)

// FakeBackendRecords implements BackendRecordInterface
type FakeBackendRecords struct {
	Fake *FakeLbcfV1beta1
	ns   string
}

var backendrecordsResource = schema.GroupVersionResource{Group: "lbcf.tkestack.io", Version: "v1beta1", Resource: "backendrecords"}

var backendrecordsKind = schema.GroupVersionKind{Group: "lbcf.tkestack.io", Version: "v1beta1", Kind: "BackendRecord"}

// Get takes name of the backendRecord, and returns the corresponding backendRecord object, and an error if there is any.
func (c *FakeBackendRecords) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.BackendRecord, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(backendrecordsResource, c.ns, name), &v1beta1.BackendRecord{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.BackendRecord), err
}

// List takes label and field selectors, and returns the list of BackendRecords that match those selectors.
func (c *FakeBackendRecords) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.BackendRecordList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(backendrecordsResource, backendrecordsKind, c.ns, opts), &v1beta1.BackendRecordList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.BackendRecordList{ListMeta: obj.(*v1beta1.BackendRecordList).ListMeta}
	for _, item := range obj.(*v1beta1.BackendRecordList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested backendRecords.
func (c *FakeBackendRecords) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(backendrecordsResource, c.ns, opts))

}

// Create takes the representation of a backendRecord and creates it.  Returns the server's representation of the backendRecord, and an error, if there is any.
func (c *FakeBackendRecords) Create(ctx context.Context, backendRecord *v1beta1.BackendRecord, opts v1.CreateOptions) (result *v1beta1.BackendRecord, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(backendrecordsResource, c.ns, backendRecord), &v1beta1.BackendRecord{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.BackendRecord), err
}

// Update takes the representation of a backendRecord and updates it. Returns the server's representation of the backendRecord, and an error, if there is any.
func (c *FakeBackendRecords) Update(ctx context.Context, backendRecord *v1beta1.BackendRecord, opts v1.UpdateOptions) (result *v1beta1.BackendRecord, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(backendrecordsResource, c.ns, backendRecord), &v1beta1.BackendRecord{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.BackendRecord), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeBackendRecords) UpdateStatus(ctx context.Context, backendRecord *v1beta1.BackendRecord, opts v1.UpdateOptions) (*v1beta1.BackendRecord, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(backendrecordsResource, "status", c.ns, backendRecord), &v1beta1.BackendRecord{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.BackendRecord), err
}

// Delete takes name of the backendRecord and deletes it. Returns an error if one occurs.
func (c *FakeBackendRecords) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(backendrecordsResource, c.ns, name), &v1beta1.BackendRecord{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBackendRecords) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(backendrecordsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.BackendRecordList{})
	return err
}

// Patch applies the patch and returns the patched backendRecord.
func (c *FakeBackendRecords) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.BackendRecord, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(backendrecordsResource, c.ns, name, pt, data, subresources...), &v1beta1.BackendRecord{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.BackendRecord), err
}
